version: "3.7"

networks:
  bridge-net-0:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
  bridge-net-1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
  bridge-net-2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.2.0/24
  bridge-net-3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.3.0/24
  router-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.4.0/24

services:
  geth-ubuntu-bootnode:
    hostname: geth-ubuntu-bootnode
    cap_add:
      - NET_ADMIN
    networks:
      bridge-net-0:
        ipv4_address: 10.1.0.10
    ports:
      - 30303:30303/udp
      - 8545:8545/tcp
      - 8080:8080/tcp
      - 8551:8551/tcp
      - 12000:12000/udp
      - 13000:13000/tcp
      - 3500:3500/tcp
      - 4000:4000/tcp
    env_file:
      - .env
    image: geth-custom:boot
    container_name: geth-bootnode
    depends_on:
      - bridge-router
    command: >-
      sh -c "cd ~ && ./run.sh"

  geth-client-1:
    hostname: geth-client-1
    cap_add:
      - NET_ADMIN
    networks:
      bridge-net-1:
        ipv4_address: 10.1.1.10
    ports:
      - 30304:30304/udp
      - 8546:8546/tcp
      - 12001:12001/udp
      - 13001:13001/tcp
      - 3501:3501/tcp
      - 8552:8552/tcp
      - 4001:4001/tcp
    env_file:
      - .env
    image: geth-custom:node1
    container_name: geth-client-1
    depends_on:
      - bridge-router
      - geth-ubuntu-bootnode
    command: sh -c "cd ~ && ./run.sh"

#  geth-client-2:
#    hostname: geth-client-2
#    cap_add:
#      - NET_ADMIN
#    networks:
#      bridge-net-2:
#        ipv4_address: 10.1.2.20
#    ports:
#      - 30305:30305/udp
#      - 8547:8547/tcp
#      - 12002:12002/udp
#      - 13002:13002/tcp
#      - 3502:3502/tcp
#      - 8553:8553/tcp
#      - 4002:4002/tcp
#    env_file:
#      - .env
#    image: geth-custom:node2
#    container_name: geth-client-2
#    depends_on:
#      - bridge-router
#      - geth-ubuntu-bootnode
#    command: sh -c "cd ~ && ./run.sh"

#  geth-client-3:
#    hostname: geth-client-3
#    cap_add:
#      - NET_ADMIN
#    networks:
#      bridge-net-3:
#        ipv4_address: 10.1.3.30
#    ports:
#      - 30306:30306/udp
#      - 8548:8548/tcp
#      - 12003:12003/udp
#      - 13003:13003/tcp
#      - 3503:3503/tcp
#      - 8554:8554/tcp
#      - 4003:4003/tcp
#    env_file:
#      - .env
#    image: geth-custom:node3
#    container_name: geth-client-3
#    depends_on:
#      - bridge-router
#      - geth-ubuntu-bootnode
#    command: sh -c "cd ~ && ./run.sh"

  bridge-router:
    image: ubuntu-with-tools
    cap_add:
      - NET_ADMIN
    hostname: bridge-router
    networks:
      bridge-net-0:
        ipv4_address: 10.1.0.2
      bridge-net-1:
        ipv4_address: 10.1.1.2
      bridge-net-2:
        ipv4_address: 10.1.2.2
      bridge-net-3:
        ipv4_address: 10.1.3.2
    command: >-
      sh -c "
      iptables -A FORWARD -i eth3 -j ACCEPT &&
      iptables -A FORWARD -i eth2 -j ACCEPT &&
      iptables -A FORWARD -i eth1 -j ACCEPT &&
      iptables -A FORWARD -i eth0 -j ACCEPT && 
      ip route del default &&
      tail -f /dev/null"
